#!/usr/bin/env python3
"""Flatten the extension's ES modules into one classic script per streaming site.

The shipped extension is Rollup output: every module is N `import {...} from
"./x.js"` lines, a body, then exactly one `export {...}` line. That regularity
means the modules can be inlined into IIFEs and wired together by hand, which
matters because WKUserScript injects classic scripts - there is no module
resolution, and no bundler available to produce one.
"""
import os
import re
import sys

IMPORT_RE = re.compile(r'^import\s*\{([^}]*)\}\s*from\s*"\./([^"]+)";\s*$')
BARE_IMPORT_RE = re.compile(r'^import\s*"\./([^"]+)";\s*$')
EXPORT_RE = re.compile(r'^export\s*\{([^}]*)\};\s*$')

SITES = {
    "netflix": "netflix.ts.js",
    "amazon": "amazon.ts.js",
    "disney": "disney.ts.js",
    "max": "max.ts.js",
    "paramount": "paramount.ts.js",
    "crunchyroll": "crunchyroll.ts.js",
}


def parse_specifiers(text):
    """'a as b, c' -> [(a, b), (c, c)]"""
    out = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        if " as " in part:
            src, dst = part.split(" as ", 1)
            out.append((src.strip(), dst.strip()))
        else:
            out.append((part, part))
    return out


class Module:
    def __init__(self, name, src):
        self.name = name
        self.imports = []      # (dep_name, [(exported_alias, local_name)])
        self.exports = []      # (local_name, exported_alias)
        body = []
        for line in src.split("\n"):
            m = IMPORT_RE.match(line)
            if m:
                self.imports.append((m.group(2), parse_specifiers(m.group(1))))
                continue
            m = BARE_IMPORT_RE.match(line)
            if m:
                self.imports.append((m.group(1), []))
                continue
            m = EXPORT_RE.match(line)
            if m:
                self.exports = parse_specifiers(m.group(1))
                continue
            body.append(line)
        self.body = "\n".join(body)


def load(src_dir, name, cache):
    if name in cache:
        return cache[name]
    with open(os.path.join(src_dir, name)) as fh:
        mod = Module(name, fh.read())
    cache[name] = mod
    for dep, _ in mod.imports:
        load(src_dir, dep, cache)
    return mod


def order(entry, cache):
    """Depth-first post-order, so every dependency is emitted before its user."""
    seen, out, stack = set(), [], set()
    def visit(name):
        if name in seen:
            return
        if name in stack:
            raise SystemExit(f"import cycle involving {name!r}; flattening assumes none")
        stack.add(name)
        for dep, _ in cache[name].imports:
            visit(dep)
        stack.discard(name)
        seen.add(name)
        out.append(name)
    visit(entry)
    return out


def emit(src_dir, site, shim_path):
    entry = SITES[site]
    cache = {}
    load(src_dir, entry, cache)
    names = order(entry, cache)

    with open(shim_path) as fh:
        shim = fh.read()

    parts = [
        f"// Generated by build-userscript.py from the extension source - do not edit.",
        f"// site: {site}   modules: {len(names)}",
        shim,
        "(function () {",
        '"use strict";',
        "var __se = {};",
    ]

    for name in names:
        mod = cache[name]
        parts.append(f'/* ---- {name} ---- */')
        parts.append(f'__se[{name!r}] = (function () {{')
        for dep, specs in mod.imports:
            if specs:
                fields = ", ".join(f"{src}: {dst}" for src, dst in specs)
                parts.append(f'var {{ {fields} }} = __se[{dep!r}];')
        parts.append(mod.body)

        # webext-bridge's port messaging needs a background page, which this host
        # has none of. Rebind the module-local `sendMessage` (declared with var at
        # `var { sendMessage, onMessage } = endpointRuntime;`) rather than only the
        # exported alias, so shared-functions' own callers - the ratings lookups -
        # reach the native bridge instead of awaiting a reply that never arrives.
        if name == "shared-functions.js":
            parts.append("sendMessage = globalThis.__seSendMessage;")

        if mod.exports:
            fields = ", ".join(f"{alias}: {local}" for local, alias in mod.exports)
            parts.append(f'return {{ {fields} }};')
        else:
            parts.append("return {};")
        parts.append("})();")

    parts.append("})();")
    return "\n".join(parts)


def main():
    src_dir, out_dir, shim_path = sys.argv[1], sys.argv[2], sys.argv[3]
    os.makedirs(out_dir, exist_ok=True)
    for site in SITES:
        js = emit(src_dir, site, shim_path)
        path = os.path.join(out_dir, f"{site}.userscript.js")
        with open(path, "w") as fh:
            fh.write(js)
        print(f"{path}: {len(js):,} bytes")


if __name__ == "__main__":
    main()
